### ISSUE TITLE
Moving sharded tensor with num_rows > 32 to device gives bad pcc

### ISSUE THREAD

**Issue by johanna-rock-tt** [tenstorrent-metal/tt-metal#6355]
**Describe the bug**
Moving a sharded tensor with height > 32 directly to device gives bad pcc; doing the same with moving the tensor to device in interleaved format and then converting to sharded works fine.

**To Reproduce**
Run `pytest models/demos/falcon40b/tests/test_falcon_mlp.py::test_FalconMLP_inference[BFLOAT16-SHARDED-0.9987-tiiuae/falcon-40b-instruct-prefill-1-64-8]`

This gives bad PCC.

Working around this issue by changing
```
    tt_mlp_input_host = torch2tt_tensor(mlp_input, None, tt_dtype=model_config["LN_MLP_OUTPUT_DTYPE"])
    tt_mlp_input = []
    for device in devices:
        tt_mlp_input.append(tt_mlp_input_host.to(device, model_config["LN_MLP_OUTPUT_MEMCFG"]))
```
 to
 
```
    tt_mlp_input_host = torch2tt_tensor(mlp_input, None, tt_dtype=model_config["LN_MLP_OUTPUT_DTYPE"])
    tt_mlp_input = []
    for device in devices:
        tt_mlp_input_per_device = tt_mlp_input_host.to(device, model_config["DEFAULT_MEMCFG"])
        tt_mlp_input_per_device = tt_lib.tensor.interleaved_to_sharded(tt_mlp_input_per_device, sharded_mem_config=model_config["LN_MLP_OUTPUT_MEMCFG"])
        tt_mlp_input.append(tt_mlp_input_per_device)
```

gives a good PCC (0.99)

**Comment by tarafdarTT** [comment]
@johanna-rock-tt can you rebase and try again. I pushed a change where we were seeing a similar bug and I fixed that. 
This PR for reference: https://github.com/tenstorrent-metal/tt-metal/pull/6381

**Comment by johanna-rock-tt** [comment]
@tarafdarTT I rebased and tried again. The issue is still there for my tests.

**Comment by tarafdarTT** [comment]
Ah okay, I'll have a look. Thanks @johanna-rock-tt

**Comment by tarafdarTT** [comment]
hey @johanna-rock-tt do you mind giving me the shard_spec and tensor sizes

**Comment by johanna-rock-tt** [comment]
hey @tarafdarTT sure! So if you run this test here in main, it will give you the failing PCC check:
`pytest models/demos/falcon40b/tests/test_falcon_mlp.py::test_FalconMLP_inference[BFLOAT16-SHARDED-0.9987-tiiuae/falcon-40b-instruct-prefill-1-64-8]`

But this is the specs:

```
      tensor shape = [1, 1, 64, 8192]
      
      shard_spec_32_cores_grid = ttl.tensor.CoreRangeSet(
          {
              ttl.tensor.CoreRange(
                  ttl.tensor.CoreCoord(0, 0),
                  ttl.tensor.CoreCoord(7, 3),
              ),
          }
      )

      model_config["LN_MLP_OUTPUT_MEMCFG"] = ttl.tensor.MemoryConfig(
          ttl.tensor.TensorMemoryLayout.WIDTH_SHARDED,
          ttl.tensor.BufferType.L1,
          ttl.tensor.ShardSpec(
              shard_spec_32_cores_grid,
              [
                  64,
                  8192 // 32,
              ],
              ttl.tensor.ShardOrientation.ROW_MAJOR,
              False,
          ),
      )
```

**Comment by TT-BrianLiu** [comment]
Did we find the bug for this issue?

**Comment by tarafdarTT** [comment]
Ah we did not. I'll look into it on Monday. I'm afk (responding via email).
I'll message Jason so that he's in the loop for this.

**Comment by tarafdarTT** [comment]
I think I've narrowed down what might be the problem. 

I've reviewed the following:
1. the allocation of the tensors between doing a direct write (which is failing) and using interleaved_to_sharded (which is passing), they are all calling the allocater the same way (the exact same arguments into the buffer constructor).
2. All buffers in both the failing and passing cases have the exact same buffer addresses. In my unit test I actually don't have any other L1 buffers so nothing else should be clashing with this.
3. The buffer mappings  could be suspect, and/or the reading and writing from it. I initially veered away from this because 1 of the 4 chips was actually correct thus indicating that the buffer mappings should be correct, but there might be uninitialized values that might be set correctly coincidentally.  This is the ONLY difference between the working and non working case. I will figure this out tonight. 

CC: @TT-BrianLiu , @tt-nshanker

**Comment by tarafdarTT** [comment]
Ah nvm there was a bug in the unit test. it looked different between tests because I tilized the tensor on host using the `to` command then sent that same tensor to all devices. 
However the first tensor swapped out the pages in-place to device order and then the subsequent tensors used that swapped buffer. I'll have a look to see if we are doing anything silly like that here.

**Comment by tarafdarTT** [comment]
```
    tt_mlp_input = []
    for device in devices:
        tt_mlp_input_host = torch2tt_tensor(mlp_input, None, tt_dtype=model_config["LN_MLP_OUTPUT_DTYPE"])
        tt_mlp_input.append(tt_mlp_input_host.to(device, model_config["LN_MLP_OUTPUT_MEMCFG"]))
        
 ```
 
 This works. Moving torch2tt_tensor inside the loop fixes it. This is a problem still but could be a sufficient workaround for now.
 Underneath the hood there is a pointer pointing to a device buffer that is being shared for some reason between device tensors.
 This only gets exposed with a direct sharded tensor because the sharded tensor does a swap of the tensor on the host, so if the tensor is already swapped then it gives in incorrect result. 
 I can raise an issue to look into this as there might be some byref in the python binding or something. However I think this  is not critical.

**Comment by tarafdarTT** [comment]
I'm tracking the other issue here as it's unrelated to sharding. 
https://github.com/tenstorrent-metal/tt-metal/issues/7039
